/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_monkey_control_MonkeyStarter */

#ifndef _Included_com_monkey_control_MonkeyStarter
#define _Included_com_monkey_control_MonkeyStarter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_monkey_control_MonkeyStarter_MK_RESULT_OK
#define com_monkey_control_MonkeyStarter_MK_RESULT_OK 1L
#undef com_monkey_control_MonkeyStarter_MK_RESULT_FAIL
#define com_monkey_control_MonkeyStarter_MK_RESULT_FAIL -1L
#undef com_monkey_control_MonkeyStarter_MK_RESULT_MISSING_CONFIg
#define com_monkey_control_MonkeyStarter_MK_RESULT_MISSING_CONFIg -2L
/*
 * Class:     com_monkey_control_MonkeyStarter
 * Method:    startMonkey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_monkey_control_MonkeyStarter_startMonkey
  (JNIEnv *, jclass);

/*
 * Class:     com_monkey_control_MonkeyStarter
 * Method:    stopMonkey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_monkey_control_MonkeyStarter_stopMonkey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
